#!/bin/sh

setbg() { 
   cp -f $1 $HOME/.config/bg.png 
   pgrep sway >/dev/null && swaymsg reload || feh --no-fehbg --bg-scale $1 
}

while read file; do
	case "$1" in
		"w") wal -i $file && cp -f $file $HOME/.config/bg.png		        ;; # set wallpaper
      "b") setbg $file             ;; # set wallpaper
      "l") betterlockscreen -u $file 	;; # set lockscreen wallpaper
		"d") trash -f $file 			        ;; # delete file
		"c") echo $file | xclip -sel c	;; # copy image path
	esac
done

