#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Get colors from .Xresources -------------------------------#
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#
# assign workspaces 
if [[ $(xrandr | grep "HDMI1 connected") ]]; then
    bspc monitor eDP1 -d 4 5 6 7 8 9
    bspc monitor HDMI1 -d 1 2 3 
else 
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
fi


workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
		let name++
	done
}
#[[ $(xrandr -q | grep "HDMI connected")  ]] || workspaces

bspc config border_width 0 
bspc config window_gap 5 
bspc config split_ratio 0.60

bspc config focused_border_color "#F2963E" 
bspc config normal_border_color "#FFF" #"$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# open firefox on 2 
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a Portmaster state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a Conky state=floating manage=off
bspc rule -a Indicator-stickynotes state=floating manage=off
#bspc rule -a zoom state=floating manage=on

# key deamon
sxhkd &

# set wallpaper 
# feh --no-fehbg --bg-scale ${HOME}/.config/bg.png

# window swallow
pgrep bspswallow || bspswallow &


