#!/usr/bin/env bash
#sachin 

# autostart = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
pgrep -x sxhkd >/dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc $HOME/.config/bspwm/keymaps &
pgrep bspswallow || bspswallow &
# feh --no-fehbg --bg-scale ${HOME}/.config/bg.png
source $HOME/.config/colors

# monitor configuration = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
# assign workspaces 
if [[ $(xrandr | grep "HDMI1 connected") ]]; then
    bspc monitor eDP1 -d 4 5 6 7 8 9
    bspc monitor HDMI1 -d 1 2 3 
else 
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
fi

# bspwm configuration = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
bspc config border_width 0 
bspc config window_gap 5 
bspc config split_ratio 0.60
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# bspwm colors = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
bspc config focused_border_color    "$YELLOW" 
bspc config normal_border_color     "$BACKGROUND"
bspc config active_border_color     "$MAGENTA"
bspc config presel_feedback_color   "$GREEN"

# window rules = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a Portmaster state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a Conky state=floating manage=off
bspc rule -a Indicator-stickynotes state=floating manage=off
bspc rule -a zoom state=floating manage=on

# end configuration = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
