#!/bin/bash 

boatHeadset="FC:58:FA:FD:71:65"

# set device
device="${boatHeadset}"

# = turn on bluetooth
#[[ $(bluetoothctl show |grep Powered: | tr '\t' ':') == ":Powered: yes" ]] || 
bluetoothctl power on

# = turn on bluetooth agent on
#bluetoothctl agent on
#bluetoothctl default-agent

# = trust and pair device
[[ $(bluetoothctl info FC:58:FA:FD:71:65 | grep Trusted: | tr '\t' ':') == ":Trusted: yes" ]] || bluetoothctl trust "${device}"
[[ $(bluetoothctl info FC:58:FA:FD:71:65 | grep Paired:  | tr '\t' ':') == ":Paired: yes"  ]] || bluetoothctl pair  "${device}"

# = connect device
#[[ $(bluetoothctl info FC:58:FA:FD:71:65 | grep Connected: | tr '\t' ':') == ":Connected: yes" ]] || 
bluetoothctl connect "${device}"
