#!/bin/bash

TERM="alacritty"
winclass=$(xdotool search --class scpad);

if [[ -z "${winclass}" ]]; then
   "${TERM}" --class "scpad" -e tmux
else
   if [[ -f /tmp/scpad ]]; then 
      rm /tmp/scpad && xdo show "${winclass}"  
   else 
      touch /tmp/scpad && xdo hide "${winclass}" 
   fi
fi

exit
